import os
from PyQt6.QtGui import QIcon

object_icon = QIcon(os.path.join(os.path.dirname(__file__), 'object.png'))
path_icon = QIcon(os.path.join(os.path.dirname(__file__), 'path.png'))
settings_icon = QIcon(os.path.join(os.path.dirname(__file__), 'settings.png'))
control_icon = QIcon(os.path.join(os.path.dirname(__file__), 'control.png'))
base_icon = QIcon(os.path.join(os.path.dirname(__file__), 'base.png'))
arrow_circle = QIcon(os.path.join(os.path.dirname(__file__), 'arrow-circle-315-left.png'))
arrow_circle_24 = QIcon(os.path.join(os.path.dirname(__file__), 'arrow-circle-double.png'))
info = QIcon(os.path.join(os.path.dirname(__file__), 'information.png'))
analyzer_icon = QIcon(os.path.join(os.path.dirname(__file__), 'analyzer.png'))
scanner_icon = QIcon(os.path.join(os.path.dirname(__file__), 'scanner.png'))
experiment_icon = QIcon(os.path.join(os.path.dirname(__file__), 'experiment.png'))
abort = QIcon(os.path.join(os.path.dirname(__file__), 'abort.png'))
update = QIcon(os.path.join(os.path.dirname(__file__), 'update.png'))
path_table = QIcon(os.path.join(os.path.dirname(__file__), 'path_table.png'))
path_file = QIcon(os.path.join(os.path.dirname(__file__), 'path_file.png'))
plot1d = QIcon(os.path.join(os.path.dirname(__file__), 'plot1d.png'))
plot2d = QIcon(os.path.join(os.path.dirname(__file__), 'plot2d.png'))
s_params = QIcon(os.path.join(os.path.dirname(__file__), 'S-params.png'))
visualiser = QIcon(os.path.join(os.path.dirname(__file__), 'visualiser-1.png'))
results = QIcon(os.path.join(os.path.dirname(__file__), 'results-1.png'))
time = QIcon(os.path.join(os.path.dirname(__file__), 'time_lable.png'))
